sudo: required
services:
  - docker

before_install:
  - docker build -t groeneboom82/docker-react -f Dockerfile.dev .


script: 
  - docker run groeneboom82/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-102447449006"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_secret_key: "$AWS_SECRET_KEY"
